apiVersion: batch/v1beta1
kind: Jobs
metadata:
  name: example-job
spec:
  template:
    spec:
      containers:
        name: example-job
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "echo hello"]
      restartPolicy: Never