apiVersion: v2
kind: Pod
metadata:
  name: example-pod-with-nginx-cmd-arg
  labels:
    name: example-pod-with-nginx-cmd-arg
    type: nginx
spec:
  containers:
  - name: myapp
    image: nginx
    command: ["nginx"]
    args: ["-g", "daemon off;", "-q"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
