apiVersion: v1
kind: Pod
metadata:
  name: example-pod-with-cpu-mem-port
  namespace: mynamespace
  labels:
    name: myapp
    type: nginx
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    port:
      - containerPort: 80
