apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  template:
    spec:
      containers:
      - name: example-job
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "echo hello"]
      restartPolicy: Never