apiVersion: v1
kind: Pod
metadata:
  name: example-pod-with-security-context
  labels:
    name: example-pod-with-security-context
    type: busybox
spec:
  securityContext:
    fsGroup: 33
    runAsUser: 33
  containers:
  - name: example-pod-with-security-context
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "whoami && echo sleeping && sleep 9999"]
    resources:
      limits:
        cpu: "2"
        memory: "200Mi"
      requests:
        cpu: "1"
        memory: "100Mi"