apiVersion: v1
kind: Pod
metadata:
  name: example-pod-with-liveness
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "500Mi"
        cpu: "2"
      requests:
        memory: "250Mi"
        cpu: "1"
    livenessProbe:
      httpGet:
        path: /
        port: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80