# This file is a template, and might need editing before it works on your project.
# include:
#   - template: Jobs/Deploy.gitlab-ci.yml

# build:
#   image: docker:latest
#   services:
#     - name: docker:18.09.7-dind
#       entrypoint: ["dockerd-entrypoint.sh"]
#       command: ["--insecure-registry", "registry.192.168.99.101.nip.io"]
#   variables:
#     DOCKER_HOST: tcp://localhost:2375
#   stage: build
#   before_script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#   script:
#     - docker build --pull -t "$CI_REGISTRY_IMAGE" .
#     - docker push "$CI_REGISTRY_IMAGE"

# Deployment step
deploy:
  stage: deploy
  image: alpine/helm:latest
  script:
    - printenv
    - helm --namespace $NAMESPACE upgrade -i $REPO_NAME --set image.tag=$TAG,env=$ENV,image.repository=$REPO_REGISTRY_URL $PATH_TO_VALUES
  # tags: # this look for k8s or dev tagged runners
  #   - k8s
  #   - dev


# deploy:
#   stage: deploy
#   script:
#     - echo "Deploy to staging server"
#   environment:
#     name: staging
#     url: https://staging.example.com
#     # kubernetes: # if not mentioned it will deploy to repoName-PROJECTID-ENV
#       # namespace: production 
      
