apiVersion: v1
kind: Pod
metadata:
  name: docker-node-js-express
  labels:
    run: docker-node-js-express
spec:
  containers:
  - name: docker-node-js-express
    image: docker_node_js_express
---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
      run: mongodbpod # this should match
spec:
  containers:
  - name: mongodb
    image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: docker-node-js-express
  labels:
    run: docker-node-js-express
spec:
  ports:
  - port: 3000
    # targetPort: 3000
    protocol: TCP
  selector:
    run: docker-node-js-express
---
  apiVersion: v1
  kind: Service
  metadata:
    name: mongodb
    labels:
      run: mongodb
  spec:
    ports:
    - port: 27017
      # targetPort: 27017
      protocol: TCP
    selector:
      run: mongodbpod # this should match