---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
      run: mongodbpod # this should match
spec:
  containers:
  - name: mongodb
    image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    run: mongodb
spec:
  ports:
  - port: 27017
    # targetPort: 27017
    protocol: TCP
  selector:
    run: mongodbpod # this should match
